### ISSUE TITLE
Assign Azure Credits has a new validation check - and the website is certificatewise bad

### ISSUE THREAD

**Issue by Williams-Nest** [MicrosoftLearning/MS-720-Microsoft-Teams-Voice-Engineer#73]
# Module: 3
#### Step: 2 and 7

Description of issue
In step 2 there is a bad web site announcement (both in Edge and in Chrome)
You will have to open and accept to proceed

In step 7 it needs a lot more (fact checked info) filling out than just that before you are allowed to click on "Sign Up"
I suggest a validated address 

Repro steps:

1.
1.
1.

**Comment by dahans-msft2** [comment]
This was fixed in PRs #53 and #54

**Comment by Williams-Nest** [comment]
I don't see any changes to get pass this issue
The certificate error is still not mentioned anywhere in the text
